{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "boundary.fullname" . }}
  labels: {{- include "boundary.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "boundary.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress]
  ingress:
    - ports:
        - {protocol: TCP, port: 8080}
      {{- with .Values.networkPolicy.ingress }}
      from: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
