{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "boundary.fullname" . }}
  labels: {{- include "boundary.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
